export { default as App } from './App';
export { AuthContextProvider, UserAuth } from './context/AuthContext';
export {  } from './main';
export { Home } from './pages/Home';
export { MyRoutes } from './routers/routes';
export { supabase } from './supabase/supabase.config';
export { DataModulosConfiguracion, DesplegableUser, LinksArray, SecondarylinksArray, TemasData, TipoDocData, TipouserData } from './utils/dataEstatica';
export * from './components/templates/HomeTemplate';
export * from './styles/breackpoints';
export * from './styles/themes';
export * from './styles/variables';
export { Device } from './styles/breackpoints';
export { Dark, Light } from './styles/themes';
export { v } from './styles/variables';
